gateway:

  security:

    upstream:
      mode: MTLS  #MTLS||TLS||NONE

      tls:
        protocol: TLSv1.3
        handshakeTimeoutMs: 10000

        keyStore:
          type: JKS #PKCS12||JKS
          path: ${GATEWAY_UPSTREAM_KEYSTORE_PATH:}
          password: ${GATEWAY_UPSTREAM_KEYSTORE_PASSWORD:}
          keyAlias: gateway-server

        trustStore:
          type: JKS #PKCS12||JKS
          path: ${GATEWAY_UPSTREAM_TRUSTSTORE_PATH:}
          password: ${GATEWAY_UPSTREAM_TRUSTSTORE_PASSWORD:}

    downstream:

      systems:

        T:
          mode: MTLS  #MTLS||TLS||NONE

          tls:
            protocol: TLSv1.3
            handshakeTimeoutMs: 10000

            keyStore:
              type: JKS #PKCS12||JKS
              path: ${GATEWAY_T_KEYSTORE_PATH:}
              password: ${GATEWAY_T_KEYSTORE_PASSWORD:}
              keyAlias: gateway-t

            trustStore:
              type: JKS #PKCS12||JKS
              path: ${GATEWAY_T_TRUSTSTORE_PATH:}
              password: ${GATEWAY_T_TRUSTSTORE_PASSWORD:}

        P:
          mode: MTLS  #MTLS||TLS||NONE

          tls:
            protocol: TLSv1.3
            handshakeTimeoutMs: 10000

            keyStore:
              type: JKS #PKCS12||JKS
              path: ${GATEWAY_P_KEYSTORE_PATH:}
              password: ${GATEWAY_P_KEYSTORE_PASSWORD:}
              keyAlias: gateway-p

            trustStore:
              type: JKS #PKCS12||JKS
              path: ${GATEWAY_P_TRUSTSTORE_PATH:}
              password: ${GATEWAY_P_TRUSTSTORE_PASSWORD:}